"""init

Revision ID: 818dc3949aac
Revises: 
Create Date: 2026-06-02 19:40:18.911145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818dc3949aac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookTitle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BookTitle_author'), 'BookTitle', ['author'], unique=False)
    op.create_index(op.f('ix_BookTitle_id'), 'BookTitle', ['id'], unique=False)
    op.create_index('title', 'BookTitle', ['author'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=False)
    op.create_table('BookCopy',
    sa.Column('id', sa.String(length=6), autoincrement=False, nullable=False),
    sa.Column('borrowing_time', sa.DateTime(), nullable=True),
    sa.Column('book_title_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['book_title_id'], ['BookTitle.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BookCopy_id'), 'BookCopy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BookCopy_id'), table_name='BookCopy')
    op.drop_table('BookCopy')
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index('title', table_name='BookTitle')
    op.drop_index(op.f('ix_BookTitle_id'), table_name='BookTitle')
    op.drop_index(op.f('ix_BookTitle_author'), table_name='BookTitle')
    op.drop_table('BookTitle')
    # ### end Alembic commands ###
